---
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Antora Playbook building current Git HEAD.
#
# See: https://docs.antora.org/antora/latest/playbook/
#
site:
  title: Antora for modular documentation
  url: https://antora-for-modular-docs.github.io/antora-for-modular-docs/
  start_page: docs::index.adoc
  robots: allow
  # keys:
  #   google_analytics: 'XXXX' # https://docs.antora.org/antora/latest/playbook/site-keys/
content:
  sources:
    - url: ./
      branches:
        - HEAD
        - v*
      edit_url: "https://github.com/antora-for-modular-docs/antora-for-modular-docs/edit/main/{path}"
asciidoc:
  attributes:
    context: docs
  sourcemap: true # https://docs.antora.org/antora/latest/playbook/asciidoc-sourcemap/
output:
  destinations:
    - provider: fs
      clean: true
      path: build/antora-for-modular-docs/
antora:
  extensions:
    - require: "@antora/lunr-extension" # https://gitlab.com/antora/antora-lunr-extension/
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
urls:
  html_extension_style: indexify
  redirect_facility: static
  # latest_prerelease_version_segment: next
  # latest_version_segment: stable
  latest_version_segment_strategy: replace
runtime:
  cache_dir: ./.cache/antora
  fetch: true
  log:
    failure_level: warn
    level: info

