---
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Antora Playbook building current Git HEAD and all `v*` branches.
#
# See: https://docs.antora.org/antora/latest/playbook/
#
site:
  title: Antora for modular documentation
  url: https://antora-for-modular-docs.github.io/antora-for-modular-docs/
  start_page: docs::index.adoc
  robots: allow
content:
  sources:
    - edit_url: "https://github.com/antora-for-modular-docs/antora-for-modular-docs/edit/main/{path}"
      branches:
        - HEAD
        - v*
      url: ./
antora:
  extensions:
    - require: "@antora/lunr-extension" # https://gitlab.com/antora/antora-lunr-extension/
    - require: "@antora/collector-extension"
asciidoc:
  attributes:
    context: docs
  sourcemap: true
  extensions:
    - asciidoctor-emoji
    - asciidoctor-kroki
ui:
  bundle:
    snapshot: true
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
  supplemental_files: ./supplemental-ui
urls:
  html_extension_style: indexify
output:
  clean: true
runtime:
  log:
    failure_level: warn
  fetch: true
