---
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Antora Playbook building current Git HEAD.
#
# See: https://docs.antora.org/antora/latest/playbook/
#
site: # https://docs.antora.org/antora/latest/playbook/configure-site/
  title: Antora for modular documentation # https://docs.antora.org/antora/latest/playbook/site-title/
  url: https://antora-for-modular-docs.github.io/antora-for-modular-docs/ # https://docs.antora.org/antora/latest/playbook/site-url/
  start_page: docs::index.adoc # https://docs.antora.org/antora/latest/playbook/site-start-page/
  robots: allow # https://docs.antora.org/antora/latest/playbook/site-robots/
  # keys:
  #   google_analytics: 'XXXX' # https://docs.antora.org/antora/latest/playbook/site-keys/
content: # https://docs.antora.org/antora/latest/playbook/configure-content-sources/
  sources:
    - url: ./
      branches: # https://docs.antora.org/antora/latest/playbook/content-branches/#current-local-branch
        - HEAD
      edit_url: "https://github.com/antora-for-modular-docs/antora-for-modular-docs/edit/main/{path}" # https://docs.antora.org/antora/latest/playbook/content-edit-url/
antora:
  extensions:
    - require: "@antora/lunr-extension" # https://gitlab.com/antora/antora-lunr-extension/
asciidoc:
  sourcemap: true # https://docs.antora.org/antora/latest/playbook/asciidoc-sourcemap/
output:
  destinations:
    - provider: fs
      clean: true
      path: build/antora-for-modular-docs/
ui: # https://docs.antora.org/antora/latest/playbook/configure-ui/
  bundle: # https://docs.antora.org/antora/latest/playbook/ui-bundle-url/
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui # https://docs.antora.org/antora/latest/playbook/ui-bundle-url/
urls: # https://docs.antora.org/antora/latest/playbook/configure-urls/
  html_extension_style: indexify # https://docs.antora.org/antora/latest/playbook/urls-html-extension-style/
  redirect_facility: static # https://docs.antora.org/antora/latest/playbook/urls-redirect-facility/
  # latest_prerelease_version_segment: next # https://docs.antora.org/antora/latest/playbook/urls-latest-prerelease-version-segment/
  # latest_version_segment: stable # https://docs.antora.org/antora/latest/playbook/urls-latest-version-segment/
  latest_version_segment_strategy: replace # https://docs.antora.org/antora/latest/playbook/urls-latest-version-segment-strategy/
runtime:
  cache_dir: ./.cache/antora # https://docs.antora.org/antora/latest/playbook/runtime-cache-dir/
  fetch: true # https://docs.antora.org/antora/latest/playbook/runtime-cache-dir/
  log:
    failure_level: warn # https://docs.antora.org/antora/latest/playbook/runtime-log-failure-level/
    level: info # https://docs.antora.org/antora/latest/playbook/runtime-log-level/
