---
# `antora-playbook.yml`
# Antora playbook.
# See https://docs.antora.org/antora/latest/playbook/
#
# Copyright (c) 2021-2023 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

site:
  url: https://antora-for-modular-docs.github.io/antora-for-modular-docs/
  title: Antora for modular documentation # Replace by your docs title
  start_page: docs::index.adoc
  robots: allow

content:
  sources:
    - url: ./
      branches: # Build current Git HEAD and all `v*` branches.
        - HEAD
        - v*
      edit_url: "https://github.com/antora-for-modular-docs/antora-for-modular-docs/edit/main/{path}"

antora:
  extensions:
    - require: '@antora/lunr-extension' # Search engine, see https://gitlab.com/antora/antora-lunr-extension/
      index_latest_only: true
      snippet_length: 142
    - require: '@antora/collector-extension' # Single-source content from engineering repositories, see https://gitlab.com/antora/antora-collector-extension
    - require: ./extensions/htmltest.js # Test links in HTML, see https://docs.antora.org/antora/latest/extend/extension-tutorial/
    - require: '@antora/pdf-extension' # Generate monolithic AsciiDoc files, see  https://gitlab.com/antora/antora-assembler

asciidoc:
  attributes:
    context: docs
  sourcemap: true

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui

urls:
  html_extension_style: indexify
  redirect_facility: static

output:
  clean: true

runtime:
  cache_dir: ./.cache/antora # Use a local directory rather than $HOME
  fetch: true
  log:
    level: info # Be more verbose than default warn level
    failure_level: warn # Fail on missing attributes
