:_module-type: PROCEDURE

[id="proc_starting-a-new-antora-project-compatible-with-modular-documentation_{context}"]
= Starting a new Antora project compatible with Modular Documentation

[role="_abstract"]
Starting a new Antora project compatible with Modular Documentation.

.Prerequisites

* Docker or Podman.

.Procedure

. Create a repository using link:https://github.com/themr0c/antora-for-modular-docs/generate[the Antora for Modular Docs repository template] and clone the repository to your local environment.

. Alternatively, download the https://github.com/themr0c/antora-for-modular-docs/archive/refs/heads/main.zip[Antora for Modular Docs zip archive], decompress it, and use the content of this archive to start a new repository.
+
----
$ cd antora-for-modular-docs
$ git init
----

. The new repository contains:

* The current documentation.
* Antora configuration, to adapt to your needs.
* A GitHub workflow to publish the docs using GitHub Pages.
* A GitHub workflow to build, validate and publish a preview for pull requests.
* Configuration to edit and build the documentation on link:https://workspaces.openshift.com[Eclipse Che hosted by Red Hat]
* Configuration for the link:https://github.com/wjdp/htmltest[`htmltest`] link checker and other tools.

. Current example defines an unique module: `end-user-guide`. Adapt the setup to your needs:

* Optionally, rename the `end-user-guide` directory.
+
TIP: Don't use the default `ROOT` module name, always use a https://docs.antora.org/antora/2.3/named-module-directory/[Named Module Directory].  
* Optionally, add a new module directory, and create the requested subdirectories. See link:https://docs.antora.org/antora/2.3/standard-directories/[Antora - Standard File and Directory Set]. 


. Edit `antora.yml`. See link:https://docs.antora.org/antora/2.3/component-version-descriptor/[What’s antora.yml?]
+
.`antora.yml`
[source,yaml,subs="+quotes,+attributes,+macros"]
----
include::example$antora.yml[]
----
<1> Mandatory component `name` with no spaces: results in an URL fragment. See link:https://docs.antora.org/antora/2.3/component-name-and-version/#name-key[Antora - name key]. Example: `docs`.
<2> Optional component title. See link:https://docs.antora.org/antora/2.3/component-title/[Antora - Customize the Title]
<3> Mandatory version name. See link:https://docs.antora.org/antora/2.3/component-name-and-version/#version-key[Antora - version key]. Set to `master` to remove the version from the page URL, see link:https://docs.antora.org/antora/2.3/component-with-no-version/[Antora - Define a Component Version with No Version].
<4> Optional version display name. Example: `Stable`. See link:https://docs.antora.org/antora/2.3/component-display-version/[Antora - Customize the Display Version]
<5> Define the start page. See: link:https://docs.antora.org/antora/2.3/component-start-page/[Antora - Choose a Start Page]
<6> Define navigation file. See: link:https://docs.antora.org/antora/2.3/component-navigation/[Antora - Assign Navigation Files to a Component Version]
<7> Define project `context`. (no spaces: results in an URL fragment) See: link:https://redhat-documentation.github.io/modular-docs/#module_anchor-and-file-names-concept[Modular Docs - File Names and Anchors]


. Edit `antora-playbook-for-development.yml`. See link:https://docs.antora.org/antora/2.3/playbook/[What’s an Antora playbook?]
+
.`antora-playbook-for-development.yml`
[source,yaml,subs="+quotes,+attributes,+macros"]
----
include::example$antora-playbook-for-development.yml[]
----
<1> Define project `title`.
<2> Define project `start_page`.


. Edit `antora-playbook.yml`
+
.`antora-playbook.yml`
[source,yaml,subs="+quotes,+attributes,+macros"]
----
include::example$antora-playbook.yml[]
----
<1> Define project `title`.
<2> Define peoject `url`
<3> Define project `start_page`.
<4> Define `google_analytics` key.
<5> Define branches to build.
<6> Define `edit_url`.

. Replace `supplemental-ui/img/project-icon.svg` by the project logo.

. Optionally, edit `supplemental-ui/partials/header-content.hbs`.

. Create an initial commit containing the result and publish to the remote Git repository.
+
----
$ git add .
$ git commit
$ git push
----

. To publish the docs using GitHub pages, enable GitHub Pages in the remote repository configuration: choose `gh-pages` as source branch, and `root` as source directory.


. To publish the build result for the pull requests:

.. Create a Netlify token `NETLIFY_AUTH_TOKEN`. See: https://app.netlify.com/user/applications/personal[Netlify - Create a new personal access token]. See: link: https://www.netlify.com/docs/cli/#obtain-a-token-in-the-netlify-ui[Obtaining a token with the UI].

.. Get a Netlify site ID `NETLIFY_SITE_ID`. See: link:https://docs.netlify.com/cli/get-started/#link-with-an-environment-variable[Link with an environment variable].

. Set the `NETLIFY_AUTH_TOKEN` and `NETLIFY_SITE_ID` environment variables in the remote git repository configuration (settings/secrets/actions). See: link:https://github.com/netlify/actions/tree/master/cli[Netlify GitHub Action CLI documentation]


.Verification


. Run preview on a local environment
+
----
./runnerpreview.sh
----

. Navigate to the remote git repository and watch for the changes in the Actions and Pages.

[role="_additional-resources"]
.Additional resources

* link:https://docs.antora.org/antora/2.3/[Antora documentation]
* link:https://docs.antora.org/antora/2.3/component-name-and-version/[Define a Component Name and Version]
* For more details on writing procedure modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].

