---
#
# Build and publish to GitHub Pages
#
# See: https://docs.antora.org/antora/2.3/publish-to-github-pages/
#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: Build and publish to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build and publish to GitHub Pages
    runs-on: ubuntu-latest
    container: "quay.io/antoraformodulardocs/antora-for-modular-docs:latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build using antora
        id: antora-build
        run: CI=true antora generate antora-playbook-for-development.yml
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/site
