---
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: Preview deploy

on:
  workflow_run:
    workflows:
      - Preview build
    types:
      - completed

jobs:
  success:
    name: Preview deploy on success
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
      - name: download preview-build artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: preview-build
      - name: Save the pull request ID
        id: pr
        run: |
          pr_number=$(cat "PR_NUMBER")
          if ! [[ "$pr_number" =~ ^[0-9]+$ ]]; then
            echo "pr number invalid"
            exit 1
          fi
          echo "PR_NUMBER=$pr_number" >> $GITHUB_ENV
          pr_sha=$(cat "PR_SHA")
          echo "PR_SHA=$pr_sha" >> $GITHUB_ENV
      - name: Deploy
        id: deploy
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          export DEPLOY_DOMAIN=https://docs-preview-pr-${{ PR_NUMBER }}.surge.sh
          echo "DEPLOY_DOMAIN=$DEPLOY_DOMAIN" >> $GITHUB_ENV
          npx surge --project build/ --domain $DEPLOY_DOMAIN --token ${{ secrets.SURGE_TOKEN }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "16"
      - name: Update status Comment
        uses: actions-cool/maintain-one-comment@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            🎊 PR Preview has been successfully built and deployed to https://devfile-docs-preview-pr-${{ steps.pr.outputs.id }}.surge.sh 🎊
            <!-- Sticky Pull Request Comment -->
          body-include: "<!-- Sticky Pull Request Comment -->"
          number: ${{ steps.pr.outputs.id }}

      - name: Job failure
        if: ${{ failure() }}
        uses: actions-cool/maintain-one-comment@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Deploy PR Preview failed.
            <!-- Sticky Pull Request Comment -->
          body-include: "<!-- Sticky Pull Request Comment -->"
          number: ${{ steps.pr.outputs.id }}

  failed:
    name: Preview deploy on failed
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'failure'
    steps:
      - name: Download PR artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: preview-build

      - name: Save the PR ID
        id: pr
        run: echo "::set-output name=id::$(<pr-id.txt)"

      - name: Job failure
        uses: actions-cool/maintain-one-comment@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Deploy PR Preview failed.
            <!-- Sticky Pull Request Comment -->
          body-include: "<!-- Sticky Pull Request Comment -->"
          number: ${{ steps.pr.outputs.id }}
